# Generated by Django 3.1.3 on 2021-03-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the Instructional Content.')),
                ('external_url', models.URLField(blank=True, default='', help_text='For example, for an external video file.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('link', 'Link'), ('text', 'Text')], default='text', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructional_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructional Content',
                'verbose_name_plural': 'Instructional Content',
            },
        ),
    ]
