# Generated by Django 3.1.5 on 2021-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0043_hackathon_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='partner_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='theme',
            field=models.CharField(default='', max_length=264),
        ),
    ]
