# Generated by Django 3.1.8 on 2021-07-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0044_auto_20210723_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='partner_only',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('organisation_only', 'Organisation Only')], default='internal', max_length=20),
        ),
    ]
