# Generated by Django 3.1.5 on 2021-08-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0044_auto_20210717_1654'),
        ('hackathon', '0045_auto_20210727_1950'),
    ]

    operations = [
    ]
