# Generated by Django 3.1.5 on 2021-08-26 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0046_merge_20210826_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='facilitators',
            field=models.ManyToManyField(blank=True, related_name='facilitated_hackathons', to=settings.AUTH_USER_MODEL),
        ),
    ]
